import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import shap
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Caching for data loading
@st.cache_data
def load_data(uploaded_file):
    return pd.read_csv(uploaded_file)

# Caching for model training (make sure the models are only trained once)
@st.cache_resource
def train_models(X_train, y_train):
    models = {
        "Linear Regression": LinearRegression(),
        "Random Forest": RandomForestRegressor(),
        "XGBoost": XGBRegressor()
    }

    # Fit models
    for name, model in models.items():
        model.fit(X_train, y_train)

    return models

st.set_page_config(page_title="Energy Generation Dashboard", layout="wide")

st.title("Piezoelectric Energy Generation Prediction")
st.write("This dashboard predicts the energy generated by piezoelectric materials based on footstep frequency and weight.")

uploaded_file = st.file_uploader("Upload a CSV file with your data", type="csv")
if uploaded_file:
    df = load_data(uploaded_file)
    st.write("Preview of Dataset:")
    st.dataframe(df)

    # Handle missing values
    if df.isnull().sum().sum() > 0:
        st.warning("Dataset contains missing values. They will be dropped.")
        df = df.dropna()

    # Select features and target
    numeric_columns = df.select_dtypes(include=np.number).columns.tolist()
    target = st.selectbox("Select the target column", numeric_columns)
    features = st.multiselect("Select feature columns", [col for col in numeric_columns if col != target])

    if features:
        X = df[features]
        y = df[target]

        # Train-test split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        st.subheader("Model Training & Evaluation")

        # Train models
        models = train_models(X_train, y_train)

        for name, model in models.items():
            y_pred = model.predict(X_test)
            mse = mean_squared_error(y_test, y_pred)
            r2 = r2_score(y_test, y_pred)
            st.markdown(f"**{name}** - R²: {r2:.4f}, MSE: {mse:.4f}")

        # User Input Prediction
        st.subheader("Try It Yourself!")
        user_input = [st.number_input(f"Enter {col}", value=float(X[col].mean())) for col in features]

        chosen_model_name = st.selectbox("Choose a model for prediction", list(models.keys()))
        chosen_model = models[chosen_model_name]
        prediction = chosen_model.predict([user_input])[0]
        st.success(f"Predicted Energy: {prediction:.2f} Joules")

        # VISUALIZATIONS
        st.header("Visualizations and Insights")

        if st.checkbox("Missing Values Heatmap"):
            fig, ax = plt.subplots()
            sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
            st.pyplot(fig)
            st.info("Highlights where data is missing. Helps identify gaps that may need preprocessing.")

        if st.checkbox("Correlation Heatmap"):
            fig, ax = plt.subplots()
            sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
            st.pyplot(fig)
            st.info("Correlation heatmap shows relationships between numeric features. High absolute values (close to 1 or -1) indicate strong correlations.")

        if st.checkbox("Pairplot"):
            fig = sns.pairplot(df[numeric_columns])
            st.pyplot(fig)
            st.info("Pairplot helps visually assess relationships between all numeric variables, aiding in understanding patterns and potential outliers.")

        if st.checkbox("Box Plot for Each Feature"):
            for col in numeric_columns:
                fig, ax = plt.subplots()
                sns.boxplot(x=df[col], ax=ax)
                st.pyplot(fig)
                st.info(f"Box plot for **{col}** shows distribution and outliers.")

        if st.checkbox("Feature Importance (Random Forest)"):
            model_rf = RandomForestRegressor()
            model_rf.fit(X, y)
            importances = pd.Series(model_rf.feature_importances_, index=X.columns)
            fig, ax = plt.subplots()
            importances.sort_values().plot(kind='barh', ax=ax)
            st.pyplot(fig)
            st.info("Feature importance shows which inputs influence the prediction most in the Random Forest model.")

        if st.checkbox("Dendrogram - Hierarchical Clustering"):
            import scipy.cluster.hierarchy as sch
            from scipy.spatial.distance import pdist

            numeric_data = df.select_dtypes(include=np.number).dropna()
            distance_matrix = pdist(numeric_data)
            linkage_matrix = sch.linkage(distance_matrix, method='ward')

            fig, ax = plt.subplots(figsize=(12, 6))
            sch.dendrogram(linkage_matrix, ax=ax)
            st.pyplot(fig)
            st.info("The dendrogram shows how samples are hierarchically clustered based on similarity. Useful for understanding nested clusters and optimal group counts.")

        if st.checkbox("Interactive SHAP Values (XGBoost)"):
            import shap
            shap.initjs()

            df_clean = df.dropna()
            X = df_clean[features]
            y = df_clean[target]

            model = XGBRegressor()
            model.fit(X, y)
            explainer = shap.Explainer(model, X)
            shap_values = explainer(X)

            st.subheader("SHAP Summary Plot")
            shap.summary_plot(shap_values, X)
            st.info("SHAP values explain the contribution of each feature to a prediction. This helps us understand how each feature is influencing the energy prediction.")

        if st.checkbox("Interactive Energy Generation Plot"):
            fig = px.scatter(df, x='Footstep Frequency', y='Weight', size='Energy Generated', title="Interactive Energy Generation")
            fig.update_layout(dragmode='zoom')
            st.plotly_chart(fig)
            st.info("This interactive plot shows how energy generation changes with footstep frequency and weight. You can zoom in/out to explore specific data points.")

        st.sidebar.markdown("### Theory Behind Piezoelectric Energy Generation")
        st.sidebar.write("""
        **Piezoelectric Materials** generate electrical energy when they experience mechanical stress. This can occur from footstep pressure, vibrations, or other forces. 
        The energy generated \(E\) is calculated as \(E = F \times d\), where \(F\) is the force applied, and \(d\) is the displacement or deformation of the material.
        """)
